### ISSUE TITLE
Transferlink only work if Visible set to true when creating the grid, not working if set to visible later

### ISSUE THREAD

**Issue by Kutez** [Frexsim/grid-pack#10]
Title.
here is the video:
https://youtu.be/PuObMQsUNLw
the code for it:
`local UIS = game:GetService("UserInputService")
local GridModule = require(game.ReplicatedStorage.Packages.GridPack)
local inventoryUI = game.Players.LocalPlayer.PlayerGui:WaitForChild("Inventory")

local grid = GridModule.createGrid({
	Parent = inventoryUI, -- Parent of the grid container.

	Visible = false,

	Assets = {
		Slot = nil, -- Add your own CanvasGroup here to customize the slots in the grid.
	},

	GridSize = Vector2.new(8, 15), -- How many slots the grid has on the X and Y axes.
	SlotAspectRatio = 1, -- Aspect ratio of one slot in the grid, helps with different resolutions if you're using scale instead of offset.

	AnchorPoint = Vector2.new(0.5, 0.5), -- Anchor point of the grid container.
	Position = UDim2.new(0.75, 0, 0.5, 0), -- Position of the grid container.
	Size = UDim2.fromScale(0.85, 0.85), -- Size of the grid container.

	Metadata = {
		-- Here you are free to store any values you want.
	},
})

local grid2 = GridModule.createGrid({
	Parent = inventoryUI, -- Parent of the grid container.

	Visible = false,

	Assets = {
		Slot = nil, -- Add your own CanvasGroup here to customize the slots in the grid.
	},

	GridSize = Vector2.new(8, 15), -- How many slots the grid has on the X and Y axes.
	SlotAspectRatio = 1, -- Aspect ratio of one slot in the grid, helps with different resolutions if you're using scale instead of offset.

	AnchorPoint = Vector2.new(0.5, 0.5), -- Anchor point of the grid container.
	Position = UDim2.new(0.25, 0, 0.5, 0), -- Position of the grid container.
	Size = UDim2.fromScale(0.85, 0.85), -- Size of the grid container.

	Metadata = {
		-- Here you are free to store any values you want.
	},
})

local myFirstItem = GridModule.createItem({
	Position = Vector2.new(0, 0), -- Position in a Grid.
	Size = Vector2.new(2, 2), -- Size in a Grid.

	Assets = {
		Item = game.ReplicatedStorage.Packages.CanvasGroup, -- Add a custom CanvasGroup here to change the item's gui element. (See customizing guide for more info)
	},

	Metadata = {
		health = 20
		-- Here you are free to store any values you want.
	},
})

local singleSlot = GridModule.createSingleSlot({
	Parent = inventoryUI, -- Parent of the slot container

	Visible = false, -- If the slot is visible, changes the containers visible property. Also disables item interaction on the item inside.

	Assets = {
		Slot = nil, -- Add your own CanvasGroup here to customize the slot.
	},

	AnchorPoint = Vector2.new(0.5, 0.5), -- Anchor point of the slot container
	Position = UDim2.new(0.5, 0, 0.5, 0), -- Position of the slot container
	Size = UDim2.fromScale(0.25, 0.5), -- Size of the slot container

	Metadata = {
		-- Here you are free to store any values you want.
	},
})

local transferLink = GridModule.createTransferLink({})
grid:AddItem(myFirstItem)

grid:ConnectTransferLink(transferLink)
singleSlot:ConnectTransferLink(transferLink)
grid2:ConnectTransferLink(transferLink)

UIS.InputBegan:Connect(function(input, gameProcessedEvent)
	if input.KeyCode == Enum.KeyCode.I and grid.GuiElement.Visible == false then
		grid.GuiElement.Visible = true
		grid2.GuiElement.Visible = true
		singleSlot.GuiElement.Visible = true
		myFirstItem.ItemElement.Visible = true
	elseif input.KeyCode == Enum.KeyCode.I and grid.GuiElement.Visible == true then
		grid.GuiElement.Visible = false
		grid2.GuiElement.Visible = false
		singleSlot.GuiElement.Visible = false
		myFirstItem.ItemElement.Visible = false
	end
end)`

The workaround is just set the visible try when creating the grid, connect to transferlink then set the visible to off. But it is a bug so

**Comment by Frexsim** [comment]
I don't have the time and energy to look into this now, expect an update this monday.

**Comment by Kutez** [comment]
Its ok, thank you for still working on this. It helps me a lot

**Comment by Frexsim** [comment]
Found out that this is not actually a bug in GridPack. You are just doing the visibility setting incorrectly. Every ItemManager has a method called :SetVisibility(), which you are not using.

Your updated code:
```lua
local UIS = game:GetService("UserInputService")
local GridModule = require(game.ReplicatedStorage.Packages.GridPack)
local inventoryUI = game.Players.LocalPlayer.PlayerGui:WaitForChild("Inventory")

local grid = GridModule.createGrid({
	Parent = inventoryUI, -- Parent of the grid container.

	Visible = false,

	Assets = {
		Slot = nil, -- Add your own CanvasGroup here to customize the slots in the grid.
	},

	GridSize = Vector2.new(8, 15), -- How many slots the grid has on the X and Y axes.
	SlotAspectRatio = 1, -- Aspect ratio of one slot in the grid, helps with different resolutions if you're using scale instead of offset.

	AnchorPoint = Vector2.new(0.5, 0.5), -- Anchor point of the grid container.
	Position = UDim2.new(0.75, 0, 0.5, 0), -- Position of the grid container.
	Size = UDim2.fromScale(0.85, 0.85), -- Size of the grid container.

	Metadata = {
		-- Here you are free to store any values you want.
	},

})

local grid2 = GridModule.createGrid({
	Parent = inventoryUI, -- Parent of the grid container.

	Visible = false,

	Assets = {
		Slot = nil, -- Add your own CanvasGroup here to customize the slots in the grid.
	},

	GridSize = Vector2.new(8, 15), -- How many slots the grid has on the X and Y axes.
	SlotAspectRatio = 1, -- Aspect ratio of one slot in the grid, helps with different resolutions if you're using scale instead of offset.

	AnchorPoint = Vector2.new(0.5, 0.5), -- Anchor point of the grid container.
	Position = UDim2.new(0.25, 0, 0.5, 0), -- Position of the grid container.
	Size = UDim2.fromScale(0.85, 0.85), -- Size of the grid container.

	Metadata = {
		-- Here you are free to store any values you want.
	},

})

local myFirstItem = GridModule.createItem({
	Position = Vector2.new(0, 0), -- Position in a Grid.
	Size = Vector2.new(2, 2), -- Size in a Grid.

	Assets = {
		Item = game.ReplicatedStorage.Packages.CanvasGroup,
	},

	Metadata = {
		health = 20
		-- Here you are free to store any values you want.
	},

})

local singleSlot = GridModule.createSingleSlot({
	Parent = inventoryUI, -- Parent of the slot container

	Visible = false, -- If the slot is visible, changes the containers visible property. Also disables item interaction on the item inside.

	Assets = {
		Slot = nil, -- Add your own CanvasGroup here to customize the slot.
	},

	AnchorPoint = Vector2.new(0.5, 0.5), -- Anchor point of the slot container
	Position = UDim2.new(0.5, 0, 0.5, 0), -- Position of the slot container
	Size = UDim2.fromScale(0.25, 0.5), -- Size of the slot container

	Metadata = {
		-- Here you are free to store any values you want.
	},

})

local transferLink = GridModule.createTransferLink({})
grid:AddItem(myFirstItem)

grid:ConnectTransferLink(transferLink)
singleSlot:ConnectTransferLink(transferLink)
grid2:ConnectTransferLink(transferLink)

UIS.InputBegan:Connect(function(input, gameProcessedEvent)
	if input.KeyCode == Enum.KeyCode.I and grid.GuiElement.Visible == false then
		grid:SetVisibility(true)
		grid2:SetVisibility(true)
		singleSlot:SetVisibility(true)
	elseif input.KeyCode == Enum.KeyCode.I and grid.GuiElement.Visible == true then
		grid:SetVisibility(false)
		grid2:SetVisibility(false)
		singleSlot:SetVisibility(false)
	end
end)
```

**Comment by Kutez** [comment]
Mb. Thanks
