### ISSUE TITLE
Typo/error in the code?

### ISSUE THREAD

**Issue by Kutez** [Frexsim/grid-pack#11]
![image](https://github.com/Frexsim/grid-pack/assets/162849091/ddcd5dc7-20dc-472d-be59-d9ffd66600f2)

 The disconnect function should use :RemoveItemManager instead of :AddItemManager right? The current system have a bug related to that but when I replace with :RemoveItemManager it works fine.

**Comment by Frexsim** [comment]
Yeah that's a typo most likely caused by autocorrect, gonna do work on a big bug fix update today so check for it later!
