### ISSUE TITLE
When you create a new item and choose the occupied position, it doesn't automatically sort the item to a new position.

### ISSUE THREAD

**Issue by c4nkerm3me** [Frexsim/grid-pack#15]
So basically, whenever you want to give yourself a tool (like a sword for example) it creates a new item, thats okay.
But, if there's already an item and you give yourself a tool, it just errors and puts the item into nowhere. If you are planning to add auto-sort or something like that, then dont forget to fix this issue too.

**Comment by Frexsim** [comment]
If you want to see if an item fits in a grid then use [`Grid:GetNextFreePositionForItem(item: Types.ItemObject)`](https://grid-pack.ifrex.xyz/api/Grid#GetNextFreePositionForItem) it returns a position or nil depending on if there is an empty space for your item.

**Comment by Frexsim** [comment]
Closing this as the solution provided should work for your case. Please comment if further attention to this is needed!
